export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const ADD_SUCCESS_FILE = 'ADD_SUCCESS_FILE'
export const ADD_FAILURE_FILE = 'ADD_FAILURE_FILE'

export const RECEIVE_CLIENTS = 'RECEIVE_CLIENTS'
export const ADD_CLIENT = 'ADD_CLIENT'
export const ADD_SUCCESS = 'ADD_SUCCESS'
export const ADD_FAILURE = 'ADD_FAILURE'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAILURE = 'UPDATE_FAILURE'

export const USER_SELECTED = 'USER_SELECTED'
export const ITEM_SELECTED = 'ITEM_SELECTED'

export const FILES_ITEM = 'FILES_ITEM'